---
Name: shop-inventory
After: ['framework/*']
Before: ['shop/*']
---
Order:
  extensions:
    - 'Milkyway\SS\Shop\Inventory\Extensions\Order'
OrderItem:
  extensions:
    - 'Milkyway\SS\Shop\Inventory\Extensions\OrderItem'
Product:
  extensions:
    - 'Milkyway\SS\Shop\Inventory\Extensions\TrackStockOnBuyable'
ProductVariation:
  extensions:
    - 'Milkyway\SS\Shop\Inventory\Extensions\TrackStockOnBuyable'
SiteConfig:
  extensions:
    - 'Milkyway\SS\Shop\Inventory\Extensions\Config'
ProductCatalogAdmin:
  extensions:
    - 'Milkyway\SS\Shop\Inventory\Extensions\ProductCatalogAdmin'

EventDispatcher:
  ShopInventory:
    listeners:
      'Milkyway\SS\Shop\Inventory\Listeners\EmailNotifications':
        events: ['zero', 'belowIndicator']

Injector:
  ProductStockDecorator:
    class: 'Milkyway\SS\Shop\Inventory\Extensions\TrackStockOnBuyable'
